# Generated by Django 5.1.5 on 2025-01-24 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Username must be alphanumeric', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
