# Generated by Django 5.1.5 on 2025-01-25 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password should contain the following: \n1. The password must be at least eight characters long \n2. The password must contain at least one uppercase letter. \n3. The password must contain at least one lowercase letter. \n4. The password must contain at least one digit. ', regex='^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$')]),
        ),
    ]
