# Generated by Django 5.1.5 on 2025-01-25 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password should contain the following: lowercase and uppercase letter, number and should be more than 8 characters long. ', regex='^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$')]),
        ),
    ]
