# Generated by Django 5.1.5 on 2025-02-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_post_likes'),
    ]

    operations = [
    ]
