# Generated by Django 5.1.5 on 2025-02-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20250227_1455'),
    ]

    operations = [
    ]
